### ISSUE TITLE
`cron_next` is giving back time in the past around the DST change

### ISSUE THREAD

**Issue by szigetics** [exander77/supertinycron#14]
I am using 

- A Windows machine
- Configured to UTC +2, Athens, Bucharest : 
<img width="667" alt="Screenshot 2024-03-18 at 09 42 26" src="https://github.com/exander77/supertinycron/assets/7099208/5148e8f5-fb11-4f90-a36e-afcadf862b6d">

- cron expression : "2 * * * * *" , which translates to "At 2 seconds past the minute" or with other words : "every minute at 2 seconds"
- time is set to 2hr:59min:02sec

Actual result : 
- `cron_next` is giving back : 2hr:00min:02sec

Expected result : 
- `cron_next` is giving back : 4hr:00min:02sec
Reason : at 03hr:00min:00sec, as DST dictates, the clock is set forward to 04hr:00min:00sec .

No matter how I configure `CRON_USE_LOCAL_TIME` the issue happens.

How could this be fixed?

**Comment by exander77** [comment]
I will try to reproduce this.

**Comment by exander77** [comment]
Seems I reproduced it (I am CET, Europe/Prague):
```
Initial: 2024-03-31_02:59:02
Expected: 2024-03-31_04:00:02
Actual: 2024-03-31_01:00:02
```

**Comment by exander77** [comment]
@szigetics Do you use musl or libc?

**Comment by exander77** [comment]
This very much seems to me like a bug in musl.

**Comment by exander77** [comment]
@szigetics Can you test latest master?

**Comment by exander77** [comment]
I rewrote tonne of code, but musl is super unreliable.
