### ISSUE TITLE
Redundant assignment, unused error out variable.

### ISSUE THREAD

**Issue by teodor-hristov** [exander77/supertinycron#17]
There are a couple of warnings that clang-tidy found. _clang-analyzer-deadcode.DeadStores_

`ccronexpr.c:603:20: error: Value stored to 'first' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
ccronexpr.c:607:20: error: Value stored to 'first' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
ccronexpr.c:619:17: error: Value stored to 'error' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]`

**Comment by exander77** [comment]
Merged.
